version: '3.1'
services:
  scout:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: scout:latest
    env_file:
      - .env
    environment:
      testvar: 123
    container_name: scout
